kind: pipeline
type: kubernetes
name: CI

trigger:
  event:
    - pull_request

steps:
  - name: integrity-check
    image: node:20.9.0-slim
    commands:
      - npm i -g @antfu/ni
      - nci
      - nr check
